Added endpoints for laevitas
dopex-io/rest-api pull request #2
Opened 2022-01-26 17:50 UTC by hellodespereaux

# Dopex REST API

**TVL**

Endpoint: https://api.dopex.io/api/v1/tvl

Method: GET

Example response:
`{"tvl":"385272088.86094545716095555338"}`

It is possible to get the TVL of only a specific subset of SSOVs using include

Example request:
https://api.dopex.io/api/v1/tvl?include=dpx-ssov,eth-ssov

Example response:
`{"tvl":"36853266.39998449803538870884"}`

Please note TVL includes both premium and deposits

------------------------------------------------------------------------------------

**Deposits per strike price**

Endpoint: https://api.dopex.io/api/v1/ssov/deposits?asset=DPX

Method: GET

Example response:
`{"deposits":{"1700":{"amount":"184.47894697001525027","usd":"356472.3588090998684017264"},"2000":{"amount":"1045.40703925883889822","usd":"2020060.9301006395798084704"},"2500":{"amount":"1029.552413371548508863","usd":"1989424.71940611061464615216"},"3333":{"amount":"4956.786392772684006099","usd":"9578097.48248251275866521968"}}}`

-------------------------------------------------------------------------------------------

**Options prices**

Endpoint: https://api.dopex.io/api/v1/ssov/options/prices?asset=DPX

Method: GET

Example response:
`{"deposits":{"55":{"premium":"0.616098743521431853","fees":"0.0025","total":"0.618598743521431853","usd":"88.18125088898011064515"},"66":{"premium":"0.539398787875357546","fees":"0.0025","total":"0.541898787875357546","usd":"77.2476722116322181823"},"88":{"premium":"0.388395108337086218","fees":"0.0025","total":"0.390895108337086218","usd":"55.7220976934516403759"},"111":{"premium":"0.245858180472895976","fees":"0.0025","total":"0.248358180472895976","usd":"35.4034586264113213788"},"133":{"premium":"0.141268471294736556","fees":"0.0025","total":"0.143768471294736556","usd":"20.4941955830646960578"}}}`

Please note usd is the equivalent value of total in USD

----------------------------------------------------------------------------------------------------------

**Options usage**

Endpoint: https://api.dopex.io/api/v1/ssov/options/usage?asset=DPX

Method: GET

Example response:
`{"total":"4017.5099","strikes":{"1700":"184.4789","2000":"1045.391","2500":"1029.546","3333":"1758.094"}}`

----------------------------------------------------------------------------------------------------------

**APY**

Endpoint: https://api.dopex.io/api/v1/ssov/apy?asset=DPX

Method: GET

Example response: 
`{"apy":41.3}`

2022-01-27 17:46 UTC, witherblock requested changes
Please explain the use case of the v2 api and why they can't be part of v1?

2022-01-27 17:46 UTC, witherblock commented on api/v2/ssov/apy/index.js
> +  console.log(supplyRatePerBlock.toNumber())
Remove the console.log

2022-01-27 17:46 UTC, witherblock commented on api/v2/ssov/apy/index.js
> +  "gmx-ssov": { fn: getGmxApy, args: [] },
Since this api is specific to ssovs, we can use a key like ETH, GOHM etc instead of eth-ssov, gohm-ssov

2022-01-27 17:46 UTC, witherblock commented on api/v2/ssov/apy/index.js
> +    if (!ssov) return;
Should not return, you have to send an error response to the request

2022-01-27 17:46 UTC, witherblock commented on api/v2/ssov/deposits/index.js
> +  "bnb-ssov": { fn: getSsovDeposits, args: ["BNB"] },
Since this api is specific to ssovs, we can use a key like ETH, GOHM etc instead of eth-ssov, gohm-ssov

2022-01-27 17:46 UTC, witherblock commented on api/v2/ssov/deposits/index.js
> +    if (!ssov) return;
Should not return, you have to send an error response to the request

2022-01-27 17:46 UTC, witherblock commented on api/v2/ssov/options/prices.js
> +  "bnb-ssov": { fn: getSsovOptionsPrices, args: ["BNB"] },
Since this api is specific to ssovs, we can use a key like ETH, GOHM etc instead of eth-ssov, gohm-ssov

2022-01-27 17:46 UTC, witherblock commented on api/v2/ssov/options/prices.js
> +    if (!ssov) return;
Should not return, you have to send an error response to the request

2022-01-27 17:46 UTC, witherblock commented on api/v2/ssov/options/usage.js
> +  "bnb-ssov": { fn: getSsovOptionsUsage, args: ["BNB"] },
Since this api is specific to ssovs, we can use a key like ETH, GOHM etc instead of eth-ssov, gohm-ssov

2022-01-27 17:46 UTC, witherblock commented on api/v2/ssov/options/usage.js
> +    if (!ssov) return;
Should not return, you have to send an error response to the request

2022-01-27 17:46 UTC, witherblock commented on api/v2/ssov/tvl/index.js
> +    if (!filter || filter.includes('gmx-ssov')) INCLUDE_QUERY_MAPPING["gmx-ssov"] = { fn: getSsovTvl, args: ["GMX"] };
Why is the api necessary if you we can use the tvl API

2022-01-27 17:46 UTC, witherblock commented on helpers/getSsovDeposits.js
> +};
move this to a common constants file

2022-01-27 17:46 UTC, witherblock commented on helpers/getSsovOptionsPrices.js
> +};
move this to a common constants file

2022-01-27 17:46 UTC, witherblock commented on helpers/getSsovOptionsUsage.js
> +};
move this to a common constants file

2022-01-27 21:05 UTC, hellodespereaux commented on api/v2/ssov/apy/index.js
> +  console.log(supplyRatePerBlock.toNumber())
done, thank you

2022-01-27 21:13 UTC, hellodespereaux commented on api/v2/ssov/apy/index.js
> +  "gmx-ssov": { fn: getGmxApy, args: [] },
Yes, we can keep this nomenclature style and add the missing functions to v1.
For some reason I assumed that there could be several SSOVs related to the same currencies but it does not make sense.
When we will have a LP SSOV we will use the LP name, if the duration of the epoch is different we can add something to the name, no need to change it.

2022-01-27 21:14 UTC, hellodespereaux commented on api/v2/ssov/apy/index.js
> +    if (!ssov) return;
ty will fix also on v1

2022-01-27 21:23 UTC, hellodespereaux commented on api/v2/ssov/tvl/index.js
> +    if (!filter || filter.includes('gmx-ssov')) INCLUDE_QUERY_MAPPING["gmx-ssov"] = { fn: getSsovTvl, args: ["GMX"] };
The TVL API gives you the total TVL of Dopex.
Laevitas is interested in the TVL of the single SSOV.

2022-01-27 21:25 UTC, hellodespereaux commented on api/v2/ssov/tvl/index.js
> +    if (!filter || filter.includes('gmx-ssov')) INCLUDE_QUERY_MAPPING["gmx-ssov"] = { fn: getSsovTvl, args: ["GMX"] };
You are right, I added there the missing keys

2022-01-27 21:42 UTC, hellodespereaux commented
Thank you, done

2022-01-29 14:22 UTC, witherblock requested changes
Fix the http status codes

Also please don't resolve and review comments, as I like to scroll through them to see what changes were made for the comment, Once u address the review comments, dm me and ill take a look and resolve them myself.

2022-01-29 14:22 UTC, witherblock commented on README.md
> -Read more here - https://vercel.com/docs/serverless-functions/introduction
Why remove this?

2022-01-29 14:22 UTC, witherblock commented on api/v1/ssov/apy/index.js
> +    if (!asset) res.status(500).json({ error: "Please send the GET parameter asset" });
Http status should be 400 (or any subset of the 400 code series) as this is an error on the client side, read more here https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

Error Message should be "Missing asset parameter."

2022-01-29 14:31 UTC, hellodespereaux commented on README.md
> -Read more here - https://vercel.com/docs/serverless-functions/introduction
Readded

2022-01-29 14:33 UTC, hellodespereaux commented on api/v1/ssov/apy/index.js
> +    if (!asset) res.status(500).json({ error: "Please send the GET parameter asset" });
Makes sense thank you

2022-01-30 13:18 UTC, witherblock requested changes

2022-01-30 13:18 UTC, witherblock commented on helpers/getSsovOptionsUsage.js
> +
does not account for BSC

2022-01-30 13:18 UTC, witherblock commented on helpers/getSsovOptionsPrices.js
> +
does not account for BSC

2022-01-30 13:18 UTC, witherblock commented on helpers/getSsovDeposits.js
> +
does not account for BSC

2022-01-30 13:18 UTC, witherblock commented on api/v1/ssov/apy/index.js
> +  return Number((((1 + gmxAprTotal / 365 / 100) ** 365 - 1) * 100).toFixed(2));
Precision will be lost

2022-01-30 13:36 UTC, hellodespereaux commented on helpers/getSsovOptionsUsage.js
> +
Fixed ty

2022-01-30 13:43 UTC, hellodespereaux commented on helpers/getSsovOptionsPrices.js
> +
fixed ty

2022-01-30 13:44 UTC, hellodespereaux commented on helpers/getSsovDeposits.js
> +
fixed ty

2022-01-30 14:26 UTC, hellodespereaux commented on api/v1/ssov/apy/index.js
> +  return Number((((1 + gmxAprTotal / 365 / 100) ** 365 - 1) * 100).toFixed(2));
console.log(gmxAprForNativeToken);
console.log(gmxAprForEsGmx);
console.log(gmxAprTotal);

16.162254179377786 ETH APR
18.07753526203036 GMX APR
34.23978944140815 TOTAL APR

https://gmx.io/earn
16.14 ETH APR
18.07 GMX APR
34.21 TOTAL APR

If you want I can use BN but it's already precise enough, I tried to be fast

2022-01-30 22:33 UTC, witherblock approved these changes
LGTM!

2022-01-30 22:34 UTC, merged